### ISSUE TITLE
capture_http doesn't work requests http/https proxies (was: capture_http and requests import order)

### ISSUE THREAD

**Issue by MaxYousif** [webrecorder/warcio#112]
How can I patch the capture_http method for the order of imports to be irrelevant? Seems that this ordering is quite problematic when importing a class (such as a web scraping class/tool) which handles all the WARC writing for you. 
There must be an easier way than including the ordered import statements in every single script which imports this scraping class/tool.

**Comment by ikreymer** [comment]
The only requirement is that `from warcio.capture_http import capture_http` appear before the first `import requests`.
The reason is that capture_http patches `httplib.HTTPConnection` which is used by `requests`.

I think you can probably have a single file, mylib.py, that includes:

The patching only needs to happen once: you can just put the the capture_http import at the beginning of your program, on even have a single file that includes both:

```
from warcio.capture_http import capture_http
import requests
```

and then use:

```
from mylib import capture_http, requests
```

It is a tradeoff to make WARC writing much easier.

Do you have an example where this would not work?

**Comment by MaxYousif** [comment]
scraper.py definition:
```
other_imports
...
from warcio.capture_http import capture_http
import requests

class Scraper:
    ...
```

main execution script:
```
from scrape_functions.scraper import capture_http, requests
from scrape_functions.scraper import Scraper

urls = [...]
scraper = Scraper(urls=urls, method='get', max_retry_attempts=10,
                                warc_file_name='testing-warc-10')
scraper.scrape()
```
The writing to WARC did not work for the above.

I then edited the ```__init__.py``` for ```scrape_functions``` to import capture_http like so:
```
from warcio.capture_http import capture_http
from .scraper import Scraper
```
The above DID work.

I will close issue since this has been solved now.

**Comment by maximusyousif** [comment]
Actually, false alarm. There is still an issue. 

I now received the 
```'NoneType' object has no attribute 'write'``` error.

Looking into this now and will try reproduce error so that I can get some help.

**Comment by MaxYousif** [comment]
Actually, false alarm.

I now receive the ```'NoneType' object has no attribute 'write'``` error.
Will try to reproduce error so that I can get some help.

**Comment by MaxYousif** [comment]
Seems like this is a python issue to do importing modules.

The following works:
 ```
from scrape_functions import scraper

scraper = scraper.Scraper(urls=urls, method='get', max_retry_attempts=10,
                                             warc_file_name='testing-warc-10')
scraper.scrape()
```

I assume the example above works because when I import all modules from `scraper`, the `capture_http` is imported before `requests`. Does anyone have any idea on how I can fix this so that I can import in the following manner `from scrape_functions.scraper import Scraper`, and still have WARC writing capabilities? Any help would be appreciated as this is driving me mad.

**Comment by MaxYousif** [comment]
Another update:

The scraping tool has now entirely fails. Any call to `capture_http` produces the following error:
```
Traceback (most recent call last):
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/scrape_functions/scraper2.py", line 449, in _send_request
    timeout=(self.max_proxy_timeout, self.read_timeout))
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/Users/Max/anaconda3/lib/python3.7/http/client.py", line 898, in _tunnel
    self.send(connect_bytes)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 118, in send
    send_request(data)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 107, in send_request
    self.recorder.write_request(buff)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 164, in write_request
    self.request_out.write(buff)
AttributeError: 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/scrape_functions/scraper2.py", line 449, in _send_request
    timeout=(self.max_proxy_timeout, self.read_timeout))
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/urllib3/connection.py", line 324, in connect
    self._tunnel()
  File "/Users/Max/anaconda3/lib/python3.7/http/client.py", line 898, in _tunnel
    self.send(connect_bytes)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 118, in send
    send_request(data)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 107, in send_request
    self.recorder.write_request(buff)
  File "/Users/Max/anaconda3/lib/python3.7/site-packages/warcio/capture_http.py", line 164, in write_request
    self.request_out.write(buff)
AttributeError: 'NoneType' object has no attribute 'write'
```

Below is the definition of the scraper object:
```
from itertools import chain
import json
import logging
from math import ceil
import multiprocessing as mp
import os
from random import choice
import shutil
import time
import traceback
import warnings

from warcio.capture_http import capture_http
from warcio.archiveiterator import ArchiveIterator
import requests

from .customwarcwriter import CustomHeaderWARCWriter


class Scraper:
    def __init__(self, urls, method, headers=None, params=None,
                 payloads=None, proxies = "storm", parse_flag='warc',
                 warc_file_name=('warc-export-' + str(int(time.time()))),
                 n_processes=mp.cpu_count(), custom_warc_headers=None,
                 previous_warc_files=None, test_proxy=False,
                 init_proxy_timeout=1.5, max_proxy_timeout=3,
                 proxy_test_sleep=0, max_retry_attempts=None,
                 read_timeout=9, between_request_wait=0,
                 terminate_status_codes=list(range(400, 432, 1)),
                 logging_file=None):

        self.supported_methods = ['get', 'post']
        self.supported_proxies = ['storm', None]
        self.supported_parse_flags = ['warc', 'memory']

        self._validate_all_scraping_configs(method=method, proxies=proxies, parse_flag=parse_flag)
        self._initialise_in_and_out_queues(previous_warc_files=previous_warc_files, urls=urls, headers=headers,params=params,
                                           payloads=payloads, custom_warc_headers=custom_warc_headers)
        self.progress_print_val = ceil(self.requests_count/100)

        self.warc_file_name = warc_file_name.replace('.warc.gz', '').replace('.warc', '')
        self.n_processes = n_processes
        self.test_proxy = test_proxy
        self.init_proxy_timeout = init_proxy_timeout
        self.max_proxy_timeout = max_proxy_timeout
        assert self.init_proxy_timeout < self.max_proxy_timeout, 'Low proxy time threshold is larger than the maximum threshold'
        self.proxy_test_sleep = proxy_test_sleep
        self.read_timeout =  read_timeout
        self.max_retry_attempts = max_retry_attempts
        self.between_request_wait = between_request_wait
        self.terminate_status_codes = terminate_status_codes
        self.logging_file = logging_file
        self.storm_proxies = [...] #omitted for this comment
        self.starting_directory = os.getcwd()
        self.instance_id = '%s_%s' % (os.getpid(), time.time())
        self.temp_folder_name = "temp_warc_scrape_results" + self.instance_id
        self.filename_template = f'{self.temp_folder_name}/{self.instance_id}_%s.warc.gz'
        os.mkdir(self.temp_folder_name)

    def __del__(self):
        try:
            os.rmdir(self.temp_folder_name)
        except:
            pass


    ##### ------ METHOD DEFINITIONS ------ #####

    def _validate_scraping_config(self, supported_list, param_input, param_name):
        """Validate the scraping configurations passed for parameters which have
        pre-defined values. This validation function is applied to the following arguements:
        1. method    2. proxies    3. parse_flag

        Arguments:
            supported_list {list} -- The list containing all the supported/accepted
            pre-defined options for a given parameter
            param_input {str} -- The parameter passed for a configuration by the user
            param_name {str} -- The string of the configuration parameter.
            This arguement is purely for the user to be able to identify
            the faulty passed parameter

        Raises:
            AssertionError: Raised when the parameter is not found in the supported list

        Returns:
            lower_case_param_input [str] -- The validated and lower cased value of the
            parameter passed by the user
        """
        if param_input is None and None in supported_list:
            return None
        if param_input is None and None not in supported_list:
            raise AssertionError(f"'None' not supported as '{param_name}' parameter")
        else:
            lower_case_param_input = param_input.lower()
            assert lower_case_param_input in supported_list, f"'{param_input}' not supported as '{param_name}' parameter"

        return lower_case_param_input

    def _validate_passed_urls(self, urls):
        """Validate each of the passed URLs to scrape. Every passed URL
        should have the protocol as part of the URL, e.g. 'https://test.com'.
        Additionally, each URL has to be a string.

        Arguments:
            urls {list} -- The list containing all the URLs to scrape

        Raises:
            AssertionError: Raised when the URL list is not of type 'list' or when
            the list is empty
            UserWarning: Raised when not all URLs passed are evaluated as valid

        Returns:
            validated_urls [list] -- The list of URLs which have been evaluated as valid
            validated_url_indexes [list] -- The list of indexes for URLs which
            have been evaluated as valid
        """
        assert isinstance(urls, list), "No URLs list object passed"
        assert len(urls) > 0, "URLs list passed is empty"
        validated_urls = [url for url in urls if type(url) == str and url.startswith("http")]
        validated_url_indexes = [i for i, url in enumerate(urls) if url in validated_urls]
        if len(validated_urls) != len(urls):
            validated_url_mismatch_warning_msg = """Not all passed URLs are valid. Please inspect the list of URLs passed
                                                    Hint: Look for URLs which are not of type 'str' and URLs not beginning with 'http'
                                                 """
            warnings.warn(validated_url_mismatch_warning_msg, UserWarning)
        return validated_urls, validated_url_indexes

    def _clean_request_details_list(self, request_details_list, list_name, keep_indexes, expected_length):
        """Clean the list of request details for a single parameter, e.g. headers.
        This function will validate that the length of the request details list is the same
        as the number of URLs to scrape. This is necessary to ensure an ordered one-to-one mapping
        between the URL to scrape and the accompanying request parameters is satisfied.
        Additionally, this function deals with None values passed for request detail parameters.

        Arguments:
            request_details_list {list} -- The list of request details to evaluate and clean
            list_name {str} -- The parameter list name, e.g. 'headers'
            keep_indexes {list} -- The list of valid URL indexes returned by '_validate_passed_urls'
            expected_length {int} -- The expected length of the request details list

        Raises:
            AssertionError: Raised when the request details list is not of
            type 'list' or when the length of the request details list mismatches
            the expected length (URLs to scrape list length)

        Returns:
            formatted_request_details_list [list] -- The list of validated and cleaned request
            details for a given parameter, e.g. headers
        """
        if request_details_list is None or request_details_list == []:
             formatted_request_details_list = [None] * expected_length
        else:
            assert isinstance(request_details_list, list), f"No {list_name} list passed"
            request_details_list = [x for i, x in enumerate(request_details_list) if i in keep_indexes]
            if len(request_details_list) == 1:
                formatted_request_details_list = request_details_list * expected_length
            else:
                assert len(request_details_list) == expected_length, f"{list_name} list length mistmatches URL length list"
                formatted_request_details_list = request_details_list

        return formatted_request_details_list

    def _parse_target_urls_from_warc_file(self, warc_file_path):
        """Parse all target URLs from a WARC file.

        Arguments:
            warc_file_path {str} -- A WARC filepath

        Returns:
            parsed_target_urls {list} -- The list of target URLs parsed from the WARC file
        """
        parsed_target_urls = []
        with open(warc_file_path, 'rb') as stream:
            for record in ArchiveIterator(stream):
                if record.rec_type == 'response':
                    if int(record.http_headers.get_statuscode()) == 200:
                        target_uri = record.rec_headers.get_header('WARC-Target-URI')
                        parsed_target_urls.append(target_uri)

        return parsed_target_urls

    def _load_previous_warc_urls(self, warc_file_path):
        """Load in all the URLs from WARC records in a given WARC file.

        Arguments:
            warc_file_path {str} -- The full filepath of the WARC to load URLs from

        Raises:
            UserWarning: Raised when the WARC filepath passed does not exist

        Returns:
            urls_to_remove [list] -- A list of URLs already scraped. These URLs should be removed
            from subsequent scraping tasks to avoid duplication
        """
        if warc_file_path is None:
            urls_to_remove = []
        else:
            if os.path.exists(warc_file_path):
                if os.path.getsize(warc_file_path) > 0 and 'warc.gz' in warc_file_path:
                    urls_to_remove = self._parse_target_urls_from_warc_file(warc_file_path=warc_file_path)
                else:
                    urls_to_remove = []
            else:
                warnings.warn('Previous WARC file path passed does not exist', UserWarning)
                urls_to_remove = []

        return urls_to_remove

    def _remove_already_scraped_urls(self, warc_file_paths, urls):
        """Remove URLs which have already been scraped. These URLs are identified
        by parsing already existing WARC files. All the URLs passed will be scraped
        without removing already scraped URLs if the 'warc_file_paths' arguement is
        set to None.

        Arguments:
            warc_file_paths {str} -- The filepath of the WARC file to parse URLs from
            urls {list} -- The list of URLs to be scraped

        Returns:
            new_urls [list] -- The list of URLs left to scrape after removing already scraped URLs
            new_url_indexes [list] -- The list of indexes for URLs which are to be scraped.
            This index list is required to ensure the one-to-one mapping of URL and request
            details such as headers
        """
        valid_urls, valid_url_indexes = self._validate_passed_urls(urls=urls)
        if warc_file_paths is None:
            new_urls = valid_urls
            new_url_indexes = valid_url_indexes
        else:
            if isinstance(warc_file_paths, list):
                already_scraper_urls_nested = [self._load_previous_warc_urls(warc_file_path=warc_file_name) for warc_file_name in warc_file_paths]
                already_scraped_urls = chain.from_iterable(already_scraper_urls_nested)
            elif isinstance(warc_file_paths, str):
                already_scraped_urls = self._load_previous_warc_urls(warc_file_path=warc_file_paths)
            new_urls = [url for url in valid_urls if url not in already_scraped_urls]
            new_url_indexes = [i for i, url in enumerate(urls) if url in new_urls]
            assert len(new_urls) > 0, "No new URLs left to scrape"

        return new_urls, new_url_indexes

    def _validate_all_scraping_configs(self, method, proxies, parse_flag):
        """Top-level function for validating the scraping configuration for 3 parameters:
        1. method    2. proxies    3. parse_flag

        Arguments:
            method {str} -- The HTTP protocol method for the requests to send.
            See 'supported_methods' attribute to see all supported methods
            proxies {str} -- The proxies to use for scraping. See 'supported_proxies'
            attribute to see all the supported proxies
            parse_flag {str} -- The flag to determine how response objects will be parsed.
            See 'supported_parse_flags' attribute to see all supported parse flags
        """
        self.method = self._validate_scraping_config(supported_list=self.supported_methods, param_input=method, param_name='method')
        self.proxies = self._validate_scraping_config(supported_list=self.supported_proxies, param_input=proxies, param_name='proxies')
        self.parse_flag = self._validate_scraping_config(supported_list=self.supported_parse_flags,param_input=parse_flag, param_name='parse_flag')

    def _validate_all_request_details(self, previous_warc_files, urls, headers, params, payloads, custom_warc_headers):
        """Top-level function to validate all the request details. The validation ensures
        that the one-to-one mapping between URL and request details remains consistent.

        Arguments:
            previous_warc_files {list} -- The list of full WARC filepaths for parsing previously scraped URLs
            urls {list} -- The list of URLs to scrape
            headers {list} -- The list of headers for all requests. Each header in the list
            will accompany a single request
            params {list} -- The list of parameters for all requests. Each params in the list
            will accompany a single request
            payloads {list} -- The list of payloads for all requests. Each payload in the list
            will accompany a single request
            custom_warc_headers {list} -- The list of custom WARC headers for all requests. Each set of
            custom WARC headers in the list will accompany a single request

        Returns:
            urls [list] -- The final list of URLs to scrape
            headers [list] -- The final list of headers for all requests.
            The list is the same length as the final list of URLs to scrape
            params [list] -- The final list of params for all requests.
            The list is the same length as the final list of URLs to scrape
            payloads [list] -- The final list of payloads for all requests.
            The list is the same length as the final list of URLs to scrape
            custom_warc_headers [list] -- The final list of custom WARC headers for all requests.
            The list is the same length as the final list of URLs to scrape
        """
        urls, new_url_indexes = self._remove_already_scraped_urls(warc_file_paths=previous_warc_files, urls=urls)
        headers = self._clean_request_details_list(request_details_list=headers, list_name='headers', keep_indexes=new_url_indexes, expected_length=len(urls))
        params = self._clean_request_details_list(request_details_list=params, list_name='params', keep_indexes=new_url_indexes, expected_length=len(urls))
        payloads = self._clean_request_details_list(request_details_list=payloads, list_name='payloads', keep_indexes=new_url_indexes, expected_length=len(urls))
        custom_warc_headers = self._clean_request_details_list(request_details_list=custom_warc_headers, list_name='custom_warc_headers', keep_indexes=new_url_indexes,
                                                               expected_length=len(urls))

        return urls, headers, params, payloads, custom_warc_headers

    def _initialise_in_and_out_queues(self, previous_warc_files, urls, headers, params, payloads, custom_warc_headers):
        """Initialise two queues as class attributes. One queue ('in_queue') contains all the
        request details for scraping desired content. The other queue ('out_queue') will store
        all the scraped results.

        Arguments:
            previous_warc_files {list} -- The list of full WARC filepaths for parsing previously scraped URLs
            urls {list} -- The list of URLs to scrape
            headers {list} -- The list of headers for all requests. Each header in the list
            will accompany a single request
            params {list} -- The list of parameters for all requests. Each params in the list
            will accompany a single request
            payloads {list} -- The list of payloads for all requests. Each payload in the list
            will accompany a single request
            custom_warc_headers {list} -- The list of custom WARC headers for all requests. Each set of
            custom WARC headers in the list will accompany a single request
        """
        urls, headers, params, payloads, custom_warc_headers = self._validate_all_request_details(previous_warc_files=previous_warc_files,
                                                                                                  urls=urls, headers=headers,
                                                                                                  params=params, payloads=payloads,
                                                                                                  custom_warc_headers=custom_warc_headers)
        request_parameters_list = [{"method": self.method, "url": url, "headers": headers, "param": param, "payload": payload,
                                    "custom_warc_headers": custom_warc_headers} for (url, headers, param, payload, custom_warc_headers)
                                    in zip(urls, headers, params, payloads, custom_warc_headers)]
        self.requests_count = len(request_parameters_list)
        manager = mp.Manager()
        self.in_queue = manager.Queue()
        for request in request_parameters_list:
            self.in_queue.put(request)
        self.out_queue = manager.Queue()
        self.failed_queue = manager.Queue()

    def _randomly_sample_storm_proxy(self):
        """Randomly sample a strom proxy. A dictionary of HTTP and HTTPS proxies
        will be returned if each request is marked to use a new proxy.
        If a new proxy for each request is not required then the dictionary
        of HTTP and HTTPS proxies will be set as a class attribute.

        Returns:
            proxy [dict] -- A dictionary cotaining HTTP and HTTPS proxies
        """
        storm_proxy = choice(self.storm_proxies)
        http_proxy = "http://{0}".format(storm_proxy)
        proxy = {"http": http_proxy, "https": http_proxy}
        return proxy

    def _proxy_test(self):
        """Attempt to sample a proxy, which has the lowest connecting/reading time
        threshold as possible. This is achieved by trying to send a GET request through
        the proxy to a test endpoint with a timeout (in seconds).
        If the connecting/reading time exceeds the threshold, then the threshold
        is increased by 0.1 seconds. This process is repeated until the
        maximum threshold is reached. Beyond the maximum threshold, the program will
        sleep for a set amount of time before re-initialising the threshold to the
        initial lowest value.

        Returns:
            proxy {dict} -- The randomly sampled proxy dictionary containing HTTP and HTTPS proxies.
            These proxies passed the threshold test
        """
        test_url = "http://www.httpbin.org/ip"
        time_min = self.init_proxy_timeout
        while True:
            if self.proxies == 'storm':
                proxy = self._randomly_sample_storm_proxy()
            elif self.proxies is None:
                proxy = None
                return proxy

            if time_min > self.max_proxy_timeout:
                print(f"Time Limit exceeded, sleeping for {self.proxy_test_sleep} seconds ...")
                time.sleep(self.proxy_test_sleep)
                time_min = self.init_proxy_timeout

            try:
                test_resp = requests.get(url=test_url, proxies=proxy, timeout=time_min)
                return proxy

            except (requests.exceptions.ReadTimeout,
                    requests.exceptions.ConnectTimeout,
                    requests.exceptions.ConnectionError):
                print("Proxy connect failed! Retrying .. ")
                time_min += 0.1

    def _return_proxy(self):
        """Top-level function for returning a proxy. This function takes into account whether
        the sampled proxy should be tested or not. If the proxy should be tested, then the sampled
        proxy is passed through the threshold test imposed by the '_proxy_test' method.

        Returns:
            proxy [dict] -- The randomly sampled proxy dictionary containing HTTP and HTTPS proxies
        """
        if self.test_proxy:
            proxy = self._proxy_test()
        else:
            if self.proxies == 'storm':
                proxy = self._randomly_sample_storm_proxy()
            elif self.proxies is None:
                proxy = None

        return proxy

    def _configure_max_attempts(self):
        """Configure the attempt parameters for sending requests.
        If 'max_retry_attempts' is set to None, then the Scraper object will only
        terminate for a given request if a terminate status code is
        observed (see 'terminate_status_codes' attribute).

        Returns:
            add_to_max_attempt [bool] -- Boolean to say whether max retry attempts is
            dynamic or static. If dynamic, then max retry attempts increases alongside
            attempts, i.e. termination is not subject to max retry attempts.
            max_attempt [int] -- The maximum number of retries to tolerate.
        """
        if self.max_retry_attempts is None:
            add_to_max_attempt = True
            max_attempt = 2
        else:
            add_to_max_attempt = False
            max_attempt = self.max_retry_attempts

        return add_to_max_attempt, max_attempt

    def _send_request(self, request_details_dict):
        """Send a request as specified by the request details dictionary passed.
        This method also takes care of configuring proxies and handles retries.
        Additionally, this function places requests which have failed into a
        failure queue.

        Arguments:
            request_details_dict {dict} -- The request details dictionary.

        Returns:
            response [requests.Response] -- The response object returned from
            sending the HTTP(s) request. This value will be None if the 'parse_flag'
            is set to 'warc'.
        """
        method = request_details_dict['method']
        url = request_details_dict['url']
        headers = request_details_dict['headers']
        data = request_details_dict['payload']
        param = request_details_dict['param']

        proxy = self._return_proxy()
        add_to_max_attempt, max_attempt = self._configure_max_attempts()
        attempt = 0
        response = None

        while (response is None) and (attempt < max_attempt):
            attempt += 1
            if add_to_max_attempt:
                max_attempt += 1

            try:
                if method == "get":
                    response = requests.get(url=url, headers=headers, params=param, proxies=proxy,
                                            timeout=(self.max_proxy_timeout, self.read_timeout))

                elif method == "post":
                    response = requests.post(url=url, headers=headers, params=param,
                                             data=data, proxies=proxy,
                                             timeout=(self.max_proxy_timeout, self.read_timeout))

                if response.status_code == 200:
                    if self.parse_flag == 'memory':
                        return response
                    else:
                        return None
                elif response.status_code in self.terminate_status_codes:
                    print(f"Received {response.status_code} HTTP Status Code - terminating ..")
                    if self.parse_flag == 'memory':
                        return response
                    else:
                        return None

                else:
                    print(f"Received {response.status_code} HTTP Status Code - retrying ..")

            except Exception as error:
                print(str(error))
                traceback.print_exc()
                pass

        self.failed_queue.put(request_details_dict)
        return None

    def _request_worker(self):
        """Top-level scraping worker function to retrieve request details
        from a queue and send the requests. This procedure is repeated until
        the requests details queue is empty.
        All the results are appended onto an output queue.
        Additionally, this function writes request and response details
        into a WARC file.
        """
        # Sleep to wait for all processes to be joined to main process
        time.sleep(2)
        pid = os.getpid()
        temp_warc_filename = self.filename_template % pid
        done_count = 0
        while self.in_queue.empty() == False:
            request_details_dict = self.in_queue.get()
            with capture_http(temp_warc_filename):
                response = self._send_request(request_details_dict=request_details_dict)
            done_count += 1
            if done_count % self.progress_print_val == 0:
                print(f"Process {pid} completed {done_count} requests")
            self.out_queue.put(response)

        return

    def _concatenate_warc_files(self):
        """Concatenate all WARC artefacts produced by each process.
        This function will produce N WARC files, each having a maximum
        size of 1GB.
        """
        warc_scrape_dir_files = [(self.temp_folder_name + '/') + file for file in os.listdir(self.temp_folder_name)]
        running_size_count = 0
        new_file_name = self.warc_file_name + ("_" + str(running_size_count) + ".warc.gz")
        for filename in warc_scrape_dir_files:
            file_size_bytes = os.path.getsize(filename)
            if os.path.exists(new_file_name):
                file_size_bytes += os.path.getsize(new_file_name)
            if file_size_bytes > 1024**3:
                running_size_count += 1
                new_file_name = self.warc_file_name + ("_" + str(running_size_count) + ".warc.gz")

            with open(filename, 'rb') as file_to_read, open(new_file_name, "ab") as main_file:
                shutil.copyfileobj(file_to_read, main_file)

        try:
            shutil.rmtree(self.temp_folder_name, ignore_errors=True)
        except:
            pass

    def scrape(self, concat_warcs=True, index_warcs=True):
        """Top-level function to launch a scraping job with the specified configurations.
        Additionally, this function can be set to concatenate all the WARC artefacts produced
        by each process, and also index the resulting WARC file.

        Keyword Arguments:
            concat_warcs {bool} -- Boolean to determine whether the WARC files produced
            by each process should be concatenated into WARC files, which max out at 1GB
            in size (default: {True})
            index_warcs {bool} -- Boolean to determine whether the resulting WARC files should
            be indexed.
        """
        processes = [mp.Process(target=self._request_worker,) for i in range(self.n_processes)]

        for process in processes:
            process.start()

        for process in processes:
            process.join()

        print('All processes completed')
        self.responses = []
        if self.parse_flag == 'memory':
            while self.out_queue.empty() == False:
                response = self.out_queue.get()
                self.responses.append(response)

        if concat_warcs:
            self._concatenate_warc_files()
```

**Comment by wumpus** [comment]
Your code works for me:

```
from scrape_functions.scraper import Scraper

urls = ['https://www.pbm.com/']

scraper = Scraper(urls=urls, method='get', max_retry_attempts=10,
                  warc_file_name='testing-warc-10', proxies=None)
scraper.scrape()
```

I have an empty scrape_functions/__init__.py

It would be better if you cut this example down to a minimal example

**Comment by MaxYousif** [comment]
Your example only works because `proxies` have been set to None. 
I have figured out where the error was and it was not warcio related so I am closing the issue.

The issue stems from HTTPS proxy support in requests (v.2.20.0). Using only HTTP proxies works fine, but using HTTPS proxies does not.

**Comment by ikreymer** [comment]
Hey, thanks for mentioning proxies, actually i think this is an issue with warcio, which I have been able to repro with the following: 
(assuming a proxy server such as pywb running on 8080)

```
from warcio.capture_http import capture_http
import requests

proxies={"http": "localhost:8080", "https": "localhost:8080"}

with capture_http('./test.warc'):
    requests.get('https://example.com/', allow_redirects=False, verify=False, proxies=proxies)
```

Will have a fix for it soon.. the http CONNECT tunnel should not be written to WARC.

**Comment by ikreymer** [comment]
@MaxYousif if you have a chance to try, see if the PR branch works for you.
Note that http proxy is also broken, it results in invalid URLs being written to the WARC.
The PR should make it work with both http and https proxies.

**Comment by MaxYousif** [comment]
Amazing, that worked for me! Thank you very much. Will this be merged into master at some point?

**Comment by wumpus** [comment]
... yes? Just like every PR. If you look at it https://github.com/webrecorder/warcio/pull/113 you can see it has a coverage issue, at the moment. Ilya is pretty aggressive at updating pypi once bugfixes make it to the end of the PR process.

**Comment by ikreymer** [comment]
Now released as warcio 1.7.3
